version: '3'
services:
  web:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
      - ./instance:/app/instance
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_RUN_HOST=0.0.0.0
    command: >
      sh -c "apt-get update && apt-get install -y git && pip install -r requirements.txt && flask run --host=0.0.0.0"
