name: Release

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "__version__.py"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Fetch all tags
        run: |
          git fetch --tags --force --prune

      - name: "Calculate version (CALVER with beta)"
        id: calver
        shell: bash
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m | sed 's/^0//')
          BASE="$YEAR.$MONTH"

          LAST_STABLE=$(git tag --list "${BASE}.*" | grep -E "^${BASE}\\.[0-9]+$" | sed -E "s#^${BASE}\.##" | sort -n | tail -n 1)
          if [ -z "$LAST_STABLE" ]; then
            LAST_STABLE=0
          fi
          NEXT=$((LAST_STABLE + 1))

          if [ "$GITHUB_REF" = "refs/heads/dev" ]; then
            BETA_COUNT=$(git tag --list "${BASE}.${NEXT}b*" | wc -l)
            BETA=$((BETA_COUNT + 1))
            VERSION="${BASE}.${NEXT}b${BETA}"
          else
            VERSION="${BASE}.${NEXT}"
          fi

          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Update __version__.py
        run: |
          cat > __version__.py <<'EOF'
          """Application version information.

          This file is automatically updated by the release workflow.
          """
          __version__ = "${{ steps.calver.outputs.version }}"
          EOF

      - name: Commit version file (no-op safe)
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        run: |
          git add __version__.py
          git commit -m "chore: bump version to ${{ steps.calver.outputs.version }}" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Create tag
        run: |
          if git rev-parse -q --verify "refs/tags/${{ steps.calver.outputs.version }}" >/dev/null; then
            echo "Tag already exists, skipping tag creation."
          else
            git tag ${{ steps.calver.outputs.version }}
            git push origin ${{ steps.calver.outputs.version }}
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.calver.outputs.version }}
          name: ${{ steps.calver.outputs.version }}
          draft: false
          prerelease: ${{ github.ref == 'refs/heads/dev' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
