name: Release

on:
  push:
    branches: [main, Dev]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate version
        id: calver
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          BASE="$YEAR.$MONTH"
          LAST=$(git tag --list "$BASE.*" | sed -e "s/$BASE.//" | sed -e 's/b//'
            | sort -n | tail -n 1)
          if [ -z "$LAST" ]; then
            PATCH=0
          else
            PATCH=$((LAST + 1))
          fi
          if [ "${{ github.ref_name }}" = "Dev" ]; then
            SUFFIX="b"
          else
            SUFFIX=""
          fi
          echo "version=$BASE.$PATCH$SUFFIX" >> "$GITHUB_OUTPUT"
      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.calver.outputs.version }}
          git push origin ${{ steps.calver.outputs.version }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.calver.outputs.version }}
          prerelease: ${{ github.ref_name == 'Dev' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
